-- metrica.hits_<id трансфера> definition

CREATE TABLE metrica.hits_<id трансфера>
(
    `CounterID` UInt32,
    `EventDate` Date,
    `CounterUserIDHash` UInt64,
    `UTCEventTime` DateTime,
    `WatchID` UInt64,
    `AdvEngineID` Nullable(UInt8),
    `AdvEngineStrID` Nullable(String),
    `BrowserCountry` Nullable(FixedString(2)),
    `BrowserEngineID` Nullable(UInt8),
    `BrowserEngineStrID` Nullable(String),
    `BrowserEngineVersion1` Nullable(UInt16),
    `BrowserEngineVersion2` Nullable(UInt16),
    `BrowserEngineVersion3` Nullable(UInt16),
    `BrowserEngineVersion4` Nullable(UInt16),
    `BrowserLanguage` Nullable(FixedString(2)),
    `CLID` Nullable(UInt32),
    `ClientIP` Nullable(UInt32),
    `ClientIP6` Nullable(FixedString(16)),
    `ClientTimeZone` Nullable(Int16),
    `CookieEnable` Nullable(UInt8),
    `DevicePixelRatio` Nullable(Float32),
    `DirectCLID` Nullable(UInt64),
    `FirstPartyCookie` Nullable(UInt64),
    `FromTag` Nullable(String),
    `GCLID` Nullable(String),
    `GoalsReached` Array(UInt32),
    `HasGCLID` Nullable(UInt8),
    `HTTPError` Nullable(UInt16),
    `IsArtifical` Nullable(UInt8),
    `IsDownload` Nullable(UInt8),
    `IsIFrame` Nullable(UInt8),
    `IsLink` Nullable(UInt8),
    `IsMobile` Nullable(UInt8),
    `IsNotBounce` Nullable(UInt8),
    `IsPageView` Nullable(UInt8),
    `IsParameter` Nullable(UInt8),
    `IsTablet` Nullable(UInt8),
    `IsTV` Nullable(UInt8),
    `JavascriptEnable` Nullable(UInt8),
    `MessengerID` Nullable(UInt8),
    `MessengerStrID` Nullable(String),
    `MobilePhoneModel` Nullable(String),
    `MobilePhoneVendor` Nullable(UInt16),
    `MobilePhoneVendorStr` Nullable(String),
    `NetworkType` Nullable(UInt8),
    `NetworkTypeStr` Nullable(String),
    `OpenstatAdID` Nullable(String),
    `OpenstatCampaignID` Nullable(String),
    `OpenstatServiceName` Nullable(String),
    `OpenstatSourceID` Nullable(String),
    `OriginalURL` Nullable(String),
    `OS` Nullable(UInt8),
    `OSFamily` Nullable(String),
    `OSName` Nullable(String),
    `OSRoot` Nullable(UInt8),
    `OSRootStr` Nullable(String),
    `OSStr` Nullable(String),
    `PageCharset` Nullable(String),
    `ParsedParams.Key1` Array(String),
    `ParsedParams.Key10` Array(String),
    `ParsedParams.Key2` Array(String),
    `ParsedParams.Key3` Array(String),
    `ParsedParams.Key4` Array(String),
    `ParsedParams.Key5` Array(String),
    `ParsedParams.Key6` Array(String),
    `ParsedParams.Key7` Array(String),
    `ParsedParams.Key8` Array(String),
    `ParsedParams.Key9` Array(String),
    `ParsedParams.Quantity` Array(UInt32),
    `QRCodeProviderID` Nullable(UInt16),
    `QRCodeProviderStrID` Nullable(String),
    `RecommendationSystemID` Nullable(UInt8),
    `RecommendationSystemStrID` Nullable(String),
    `Referer` Nullable(String),
    `RegionID` Nullable(UInt32),
    `ResolutionDepth` Nullable(UInt8),
    `ResolutionHeight` Nullable(UInt16),
    `ResolutionWidth` Nullable(UInt16),
    `SearchEngineID` Nullable(UInt16),
    `SearchEngineRootID` Nullable(UInt16),
    `SearchEngineRootStrID` Nullable(String),
    `SearchEngineStrID` Nullable(String),
    `ShareService` Nullable(String),
    `ShareTitle` Nullable(String),
    `ShareURL` Nullable(String),
    `SocialSourceNetworkID` Nullable(UInt8),
    `SocialSourceNetworkStrID` Nullable(String),
    `SocialSourcePage` Nullable(String),
    `Title` Nullable(String),
    `TrafficSourceID` Nullable(Int8),
    `TrafficSourceStrID` Nullable(String),
    `URL` Nullable(String),
    `UserAgent` Nullable(UInt8),
    `UserAgentMajor` Nullable(UInt16),
    `UserAgentStr` Nullable(String),
    `UserAgentVersion2` Nullable(UInt32),
    `UserAgentVersion3` Nullable(UInt32),
    `UserAgentVersion4` Nullable(UInt32),
    `UTMCampaign` Nullable(String),
    `UTMContent` Nullable(String),
    `UTMMedium` Nullable(String),
    `UTMSource` Nullable(String),
    `UTMTerm` Nullable(String),
    `WindowClientHeight` Nullable(UInt16),
    `WindowClientWidth` Nullable(UInt16),
    `YQRID` Nullable(String)
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/metrica.hits_<id трансфера>_cdc',
 '{replica}')
PARTITION BY toMonday(EventDate)
ORDER BY (CounterID,
 EventDate,
 CounterUserIDHash,
 UTCEventTime)
SAMPLE BY CounterUserIDHash
SETTINGS index_granularity = 8192;